services:

  cdn-storage:
    image: ghcr.io/fehmicorp/cdn-storage:latest
    container_name: cdn-storage
    restart: unless-stopped

    ports:
      - "8081:9001"

    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_REGION: ${MINIO_REGION}
      MINIO_REGION_NAME: ${MINIO_REGION_NAME}

    volumes:
      - ./data/cdn:/data
  
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped

    ports:
      - "80:80"
    
    environment:
      CDN_SERVER_API_KEY: ${CDN_SERVER_API_KEY}
      CDN_FRONTEND_API_KEY: ${CDN_FRONTEND_API_KEY}

    volumes:
      - ./nginx.conf:/etc/nginx/templates/default.conf.template:ro

    depends_on:
      - cdn-storage