events {}

http {
    server {
        listen 80;

        location /cdn/ {
            proxy_pass http://cdn-storage:9000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}